### PR TITLE
Hotfix coconut 1

### PR DESCRIPTION
**Pull request by maryansnake**
coconut

### CODE REVIEW

**Comment by Marko-Shevchuk** [comment]
good security!

**Review by Marko-Shevchuk — APPROVED** [review]

**Review by maidennnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn — APPROVED** [review]
man idc about nothing this here is THE best feature that could ever exist

**Review by sgorrister — APPROVED** [review]
gavno👍

**Comment by maryansnake** [comment]
> man idc about nothing this here is THE best feature that could ever exist

in my opinion this is the only one feature that make that project great

**Review by nataliiatymkiv — APPROVED** [review]

**Pull request merged**
